Add basic Postgres connection/query example
jason5122/4156-team-project pull request #2
Opened 2024-10-09 21:29 UTC by jason5122

* Install JDBC dependency
* Add JDBC example code for connection and query

2024-10-09 21:32 UTC, ellayunjikim requested changes
Add a TODO for the databaseExperiment

2024-10-09 21:33 UTC, ellayunjikim commented on src/main/java/dev/coms4156/project/teamproject/App.java
> +    private static void databaseExperiment() {
Add a todo here

2024-10-09 22:33 UTC, jason5122 commented on src/main/java/dev/coms4156/project/teamproject/App.java
> +    private static void databaseExperiment() {
Done!

2024-10-14 23:39 UTC, jason5122 commented
This is obsolete since we're using JPA now.

2024-10-14 23:39 UTC, closed without merging